---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170809213747"
editor:
  name: "AddTravisWebhookEditor"
  group: "spildrazil"
  artifact: "spring-team-handlers"
  version: "0.8.129"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers"
    branch: "master"
    sha: "b70d3b6*"
  parameters:
    - "atomistWebhookUrl": "https://webhook-staging.atomist.services/atomist/travis"

